proxy-groups:
  - name: 节点选择
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 手动切换
      - 手动切换组2
      - 手动切换组3
      - 故障转移
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 英国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
      - 德国节点
      - 法国节点
      - 加拿大节点
      - 尼日利亚节点
      - 美国家宽
      - 日本家宽
      - 家宽节点
      - DIRECT
  - name: 故障转移
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
    type: fallback
    url: https://cp.cloudflare.com/generate_204
    proxies:
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 日本节点
      - 新加坡节点
      - 手动切换
      - DIRECT
    interval: 180
    tolerance: 20
    lazy: false
  - name: 手动切换
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 手动切换组2
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 手动切换组3
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 静态资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    proxies: &a1
      - 节点选择
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 英国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
      - 德国节点
      - 法国节点
      - 加拿大节点
      - 手动切换组2
      - 手动切换组3
      - 全球直连
  - name: 人工智能
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    type: select
    proxies: &a2
      - 节点选择
      - 美国家宽
      - 日本家宽
      - 家宽节点
      - 手动切换组2
      - 手动切换组3
      - 全球直连
  - name: 加密货币
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cryptocurrency_3.png
    type: select
    proxies: *a1
  - name: PayPal
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/PayPal.png
    type: select
    proxies: *a2
  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies: *a1
  - name: Microsoft
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png
    type: select
    proxies: *a1
  - name: Bing
    icon: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/Icons/Bing.png
    type: select
    proxies: *a2
  - name: Apple
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple_2.png
    type: select
    proxies: *a1
  - name: Google
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies: *a1
  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies: *a1
  - name: Netflix
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies: *a1
  - name: Spotify
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    type: select
    proxies: *a1
  - name: TikTok
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png
    type: select
    proxies: *a2
  - name: E-Hentai
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Ehentai.png
    type: select
    proxies: *a1
  - name: PikPak
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/PikPak.png
    type: select
    proxies: *a1
  - name: 巴哈姆特
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bahamut.png
    type: select
    proxies:
      - 台湾节点
      - 香港节点
      - 节点选择
      - 全球直连
  - name: 哔哩哔哩
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png
    type: select
    proxies:
      - 全球直连
      - 台湾节点
      - 香港节点
  - name: Twitter(X)
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    type: select
    proxies: *a1
  - name: 新浪微博
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Weibo.png
    type: select
    proxies: *a1
  - name: 学术资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Scholar.png
    type: select
    proxies:
      - 节点选择
      - 手动切换
      - 手动切换组2
      - 手动切换组3
      - 全球直连
  - name: 开发者资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png
    type: select
    proxies: *a1
  - name: 瑟琴网站
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Pornhub.png
    type: select
    proxies: *a1
  - name: 游戏平台
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    type: select
    proxies: *a1
  - name: 测速服务
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png
    type: select
    proxies: *a1
  - name: FCM推送
    icon: https://testingcf.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png
    type: select
    proxies:
      - 全球直连
      - Google
      - 节点选择
  - name: SSH(22端口)
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Server.png
    type: select
    proxies: *a1
  - name: 搜狗输入
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Sougou.png
    type: select
    proxies:
      - 全球直连
      - REJECT
  - name: 全球直连
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 节点选择
  - name: 广告拦截
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - 全球直连
  - name: 香港节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)^(?!.*游戏).*(香港|港|\bHK\b|Hong\s?Kong|HongKong|hongkong).*
    type: select
  - name: 澳门节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Macao.png
    include-all: true
    filter: (?i)澳门|MO|Macau
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: 台湾节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan
    type: select
  - name: 美国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)^(?!.*家宽).*(美国|US|United States)
    type: select
  - name: 英国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_Kingdom.png
    include-all: true
    filter: (?i)英国|United Kingdom|UK|伦敦|London
    type: select
  - name: 日本节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)^(?!.*(?:家宽|游戏|星链|starlink|5G)).*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: 韩国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Korea.png
    include-all: true
    filter: (?i)KR|Korea|KOR|首尔|韩|韓
    type: select
  - name: 新加坡节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: (?i)新加坡|坡|狮城|SG|Singapore
    type: select
  - name: 德国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Germany.png
    include-all: true
    filter: (?i)德国|DE|Germany
    type: select
  - name: 法国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/France.png
    include-all: true
    filter: (?i)法国|FR|France
    type: select
  - name: 加拿大节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Canada.png
    include-all: true
    filter: (?i)加拿大|Canada|CA
    type: select
  - name: 尼日利亚节点
    icon: https://www.emojiall.com/images/240/twitter/twemoji-15.0.1/1f1f3-1f1ec.png
    include-all: true
    filter: (?i)尼日利亚|NG|Nigeria
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 180
    tolerance: 20
    lazy: false
  - name: 美国家宽
    icon: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/Icons/United_States-resident.png
    include-all: true
    filter: (?i)(?=.*(?:美国|US|United States))(?=.*家宽)
    type: select
    url: https://cp.cloudflare.com/generate_204
  - name: 日本家宽
    icon: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/Icons/Japan-resident.png
    include-all: true
    filter: (?i)(?=.*(?:日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan))(?=.*(?:家宽|星链|starlink|5G))(?!.*游戏)
    type: select
    url: https://cp.cloudflare.com/generate_204
  - name: 家宽节点
    icon: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/Icons/Resident.png
    include-all: true
    filter: (?i)(?=.*(?:家宽|星链|住宅|starlink|5G))(?!.*游戏)
    type: select
    url: https://cp.cloudflare.com/generate_204
  - name: GLOBAL
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    type: select
    proxies:
      - 节点选择
      - 故障转移
      - 手动切换
      - 手动切换组2
      - 手动切换组3
      - 静态资源
      - 人工智能
      - 加密货币
      - PayPal
      - Telegram
      - Microsoft
      - Apple
      - Google
      - YouTube
      - Netflix
      - Spotify
      - TikTok
      - E-Hentai
      - PikPak
      - 巴哈姆特
      - 哔哩哔哩
      - Twitter(X)
      - 新浪微博
      - 学术资源
      - 开发者资源
      - 瑟琴网站
      - 游戏平台
      - 测速服务
      - FCM推送
      - SSH(22端口)
      - 搜狗输入
      - 全球直连
      - 广告拦截
      - 香港节点
      - 澳门节点
      - 台湾节点
      - 美国节点
      - 英国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
      - 德国节点
      - 法国节点
      - 加拿大节点
      - 尼日利亚节点
      - 美国家宽
      - 日本家宽
      - 家宽节点
rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://adrules.top/adrules_domainset.txt
    path: ./ruleset/ADBlock.txt
  SogouInput:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt
    path: ./ruleset/SogouInput.txt
  StaticResources:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./ruleset/StaticResources.txt
  CDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./ruleset/CDNResources.txt
  AI:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./ruleset/AI.txt
  TikTok:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/TikTok.list
    path: ./ruleset/TikTok.list
  EHentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/EHentai.list
    path: ./ruleset/EHentai.list
  SteamFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/SteamFix.list
    path: ./ruleset/SteamFix.list
  GoogleFCM:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./ruleset/FirebaseCloudMessaging.list
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
    path: ./ruleset/AdditionalFilter.list
  Weibo:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/Weibo.list
    path: ./ruleset/Weibo.list
  AdditionalCDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalCDNResources.list
    path: ./ruleset/AdditionalCDNResources.list
  SpeedTest:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/speedtest.txt
    path: ./ruleset/SpeedTest.list
  Paga:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/RuleSet/Paga.list
    path: ./ruleset/Paga.list
  WeChat:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/WeChat/WeChat.list
    path: ./ruleset/WeChat.list
  Brokers:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/RuleSet/Brokers.list
    path: ./ruleset/Brokers.list
  HKBank:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/RuleSet/HKBank.list
    path: ./ruleset/HKBank.list
  USCarrier:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/RuleSet/USCarrier.list
    path: ./ruleset/USCarrier.list
  RejectHTTPDNS:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/RuleSet/NOHTTPDNS.list
    path: ./ruleset/NOHTTPDNS.list
  bilibili:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/itsCheney/StashConfig/RuleSet/Bilibili.list
    path: ./ruleset/Bilibili.list
rules:
  - DOMAIN,upos-hz-mirrorakam.akamaized.net,全球直连
  - RULE-SET,RejectHTTPDNS,REJECT
  - RULE-SET,USCarrier,美国家宽
  - RULE-SET,Paga,尼日利亚节点
  - RULE-SET,HKBank,全球直连
  - RULE-SET,WeChat,全球直连
  - RULE-SET,ADBlock,广告拦截
  - RULE-SET,AdditionalFilter,广告拦截
  - RULE-SET,SogouInput,搜狗输入
  - RULE-SET,StaticResources,静态资源
  - RULE-SET,CDNResources,静态资源
  - RULE-SET,AdditionalCDNResources,静态资源
  - RULE-SET,AI,人工智能
  - RULE-SET,EHentai,E-Hentai
  - RULE-SET,TikTok,TikTok
  - RULE-SET,SteamFix,全球直连
  - RULE-SET,GoogleFCM,FCM推送
  - RULE-SET,Weibo,新浪微博
  - RULE-SET,SpeedTest,测速服务
  - RULE-SET,Brokers,全球直连
  - RULE-SET,bilibili,哔哩哔哩
  - DOMAIN,services.googleapis.cn,全球直连
  - GEOSITE,duolingo,节点选择
  - GEOSITE,bing,Bing
  - GEOSITE,paypal@cn,全球直连
  - GEOSITE,paypal,PayPal
  - GEOSITE,google-play@cn,全球直连
  - GEOSITE,apple@cn,全球直连
  - GEOSITE,apple,Apple
  - GEOSITE,telegram,Telegram
  - GEOSITE,youtube@cn,全球直连
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,netflix,Netflix
  - GEOSITE,spotify,Spotify
  - GEOSITE,twitter,Twitter(X)
  - GEOSITE,bahamut,巴哈姆特
  - GEOSITE,category-dev,开发者资源
  - GEOSITE,category-porn,瑟琴网站
  - GEOSITE,category-games@cn,全球直连
  - GEOSITE,category-games,游戏平台
  - GEOSITE,category-scholar-!cn,学术资源
  - GEOSITE,category-scholar-cn,全球直连
  - GEOSITE,category-cryptocurrency,加密货币
  - GEOSITE,microsoft@cn,全球直连
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,pikpak,PikPak
  - GEOSITE,cn,全球直连
  - GEOSITE,private,全球直连
  - GEOIP,NETFLIX,Netflix,no-resolve
  - GEOIP,GOOGLE,Google,no-resolve
  - GEOIP,TELEGRAM,Telegram,no-resolve
  - GEOIP,CN,全球直连,no-resolve
  - GEOIP,LAN,全球直连,no-resolve
  - GEOIP,PRIVATE,全球直连,no-resolve
  - DST-PORT,22,SSH(22端口)
  - MATCH,节点选择
sniffer:
  sniff:
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080
        - 8880
    QUIC:
      ports:
        - 443
        - 8443
  override-destination: false
  enable: true
  force-dns-mapping: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.push.apple.com
dns:
  enable: true
  ipv6: false
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - geosite:private
    - geosite:connectivity-check
    - geosite:cn
    - Mijia Cloud
    - dig.io.mi.com
    - localhost.ptlogin2.qq.com
    - "*.icloud.com"
    - "*.stun.*.*"
    - "*.stun.*.*.*"
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - system
    - 223.5.5.5
    - 119.29.29.29
    - 180.184.1.1
  fallback:
    - quic://dns0.eu
    - https://dns.cloudflare.com/dns-query
    - https://dns.sb/dns-query
    - tcp://208.67.222.222
    - tcp://8.26.56.2
  proxy-server-nameserver:
    - quic://223.5.5.5
    - tls://dot.pub
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
  asn: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb
