name: Convert Multiple Clash Domain Rules from URLs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    

    permissions:
      contents: write

    strategy:
      matrix:
        url:
          - 'https://ruleset.skk.moe/Clash/domainset/cdn.txt'
      fail-fast: false 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run rule conversion script for ${{ matrix.url }}
        env:
          CLASH_DOMAINS_URL: ${{ matrix.url }}
        run: python ./.github/workflows/ClashRulesConverter.py

      - name: Commit and push if changed
        run: |
          FILENAME=$(basename "${{ matrix.url }}")
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add ConvertedRules/
          
          if [ -z "$(git status --porcelain)" ]; then
            echo "规则无变化，无需提交。"
          else
            git commit -m "docs(rules): 自动更新规则: $FILENAME"
            git push
          fi
